### ISSUE TITLE
Undefined language contribution

### ISSUE THREAD

**Issue by aegatlin** [phoenixframework/vscode-phoenix#3]
First of all, you are a hero for enabling this syntax support. 👏 

Second, there seems to be a bug related to an undefined language contribution. See the screenshot. It doesn't affect the syntax highlighting from what I can tell.

<img width="1084" alt="Screen Shot 2021-09-13 at 8 16 16 am" src="https://user-images.githubusercontent.com/10734306/133004549-271cf7f1-08ba-453b-8f8d-a6eaef48d3fe.png">

**Comment by karamfd** [comment]
The "language" is missing in the package.json file. Here is a sample of the current package.json file:

{
        "scopeName": "source.elixir.heex",
        "path": "./syntaxes/elixir-heex.json",
        "injectTo": [
          "source.elixir"
        ]
}

Below is an example of how to fix it:

{
       "language": "elixir",
        "scopeName": "source.elixir.heex",
        "path": "./syntaxes/elixir-heex.json",
        "injectTo": [
          "source.elixir"
        ]
}

I'm not sure if you meant to add elixir as a language. Please let me know if that's the case so I can fix it and submit a pull request.
