### ISSUE TITLE
Code formatting support

### ISSUE THREAD

**Issue by NatoBoram** [phoenixframework/vscode-phoenix#6]
The new Phoenix LiveView release supports a new `.html.heex` and `~H` template engine, which deprecates `.eex`, `.leex` and `~L`. It would be nice to have auto-formatting support for these.

* https://github.com/adamzapasnik/prettier-plugin-eex/issues/71
* https://github.com/beautify-web/js-beautify/issues/1964
* https://github.com/elixir-lsp/vscode-elixir-ls/issues/162
* https://github.com/elixir-lsp/vscode-elixir-ls/issues/201
* https://github.com/elixir-lsp/vscode-elixir-ls/issues/98
* https://github.com/elixir-lsp/vscode-elixir-ls/pull/193
* https://github.com/phoenixframework/phoenix_live_view/pull/1904
* https://github.com/phoenixframework/vscode-phoenix/issues/6
* https://github.com/prettier/prettier/issues/12269

**Comment by NatoBoram** [comment]
This just happened

* https://github.com/phoenixframework/phoenix_live_view/pull/1904

**Comment by NatoBoram** [comment]
> # Changelog
> 
> ## 0.17.8 (2022-04-06)
> 
> ### Enhancements
>   - Add HEEx formatter

https://github.com/phoenixframework/phoenix_live_view/blob/v0.17.8/CHANGELOG.md

**Comment by josevalim** [comment]
The formatting should happen as part of the regular Elixir tooling. :)
