### ISSUE TITLE
Emmet Support Instructions

### ISSUE THREAD

**Issue by karamfd** [phoenixframework/vscode-phoenix#8]
To use emmet auto-completion in this extension, add the options below in your settings:

"emmet.includeLanguages": {
    "phoenix-heex": "html"
  },

I'll make a Pull Request with these instructions, if that's alright with you 🙂

**Comment by karamfd** [comment]
I made a pull request to address this issue and it's been merged.

**Comment by miXwui** [comment]
Just an update to this issue, I had to also add this line:

```json
"emmet.includeLanguages": {
...
  "elixir": "html"
},
```

to get Emmet abbreviations to work inside ~H sigils.

Created pull request https://github.com/phoenixframework/vscode-phoenix/pull/11 to update the readme  :slightly_smiling_face:
